version: '3'
services:
  mysql:
    container_name: mud-mariadb
    image: mariadb:10.9.3
    platform: linux/amd64
    environment:
      MYSQL_MULTIPLE_DATABASES: mud
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
      - mysql-conf:/etc/mysql/conf.d
volumes:
  mysql-data:
    driver: local
  mysql-conf:
    driver: local
